version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hash
      POSTGRES_PASSWORD: hash3hash
      POSTGRES_DB: smile_app_dev

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080
# docker compose -f docker-compose.yml -f docker-compose.production.yml up --build
